repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(.bumpversion.cfg)$'
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: '^(honyaku/.*|tests/.*)\.py$'
        arguments: --ignore=E712